tuning the circleci pipeline (#2990)
* circle-annotate pr commit status

* faster yarn install without check-cache

* make use of github status - ORB

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,4 +1,6 @@
 version: 2.1
+orbs:
+  github-status: assurance-maladie-digital/github-status@1.3.0
 
 parameters:
   test-url:
@@ -12,10 +14,65 @@ parameters:
 workflows:
   all:
     jobs:
-      #- install_and_cache
-      - test
+      - pr-pending
+      - test:
+          requires:
+            - pr-pending
+      - pr-success:
+          requires:
+            - test
+      # LATER- report-failed-status-only-custom: requires: - test
+
+executors:
+  executor_with_curl:
+    docker:
+      - image: cimg/base:stable
 
 jobs:
+  pr-pending:
+    executor: executor_with_curl
+    environment:
+      DEBUG: true
+    steps:
+      - run: echo "export TARGET_URL=$CIRCLE_BUILD_URL" >> $BASH_ENV
+      - github-status/pending:
+          description: pending
+          context: e2e/cypress-test
+  report-failed-status-only:
+    executor: executor_with_curl
+    steps:
+      - run: exit 1
+      - github-status/report_failed_only
+  report-failed-status-only-custom:
+    executor: executor_with_curl
+    steps:
+      - run: echo "export TARGET_URL=$CIRCLE_BUILD_URL" >> $BASH_ENV
+      - run: exit 1
+      - github-status/report_failed_only:
+          context: ci/integration
+          description: "Integration pipeline failed"
+
+  pr-success:
+    executor: executor_with_curl
+    environment:
+      CYPRESS_baseUrl: << pipeline.parameters.test-url >>
+      DEBUG: true
+    steps:
+      - run:
+          name: pre-check for params
+          command: |
+            if [  "x" == "x${CYPRESS_baseUrl}"  ] ;  then
+              circleci step halt # does nothing
+              circleci-agent step halt # does nothing
+
+              echo "   No parameters -skipping build ..."
+              exit 0
+            fi
+      - github-status/post_status:
+          context: e2e/cypress-test
+          description: success
+          state: success
+
   install_and_cache:
     docker:
       - image: cypress/base:20.11.0
@@ -38,61 +95,47 @@ jobs:
     docker:
       - image: cypress/base:20.11.0
     resource_class: lowsky/selfhosted
+    environment:
+      CYPRESS_baseUrl: << pipeline.parameters.test-url >>
+      EXPECTED_GIT_SHA: << pipeline.parameters.deployed-sha >>
+      CYPRESS_branch: ${CIRCLE_BRANCH}
     steps:
       - run:
-          name: Use parameters
+          name: Check if parameters for PR-run exist
           command: |
-            echo parameters:
-            echo test-url: << pipeline.parameters.test-url >>
-            echo deployed-sha: <<pipeline.parameters.deployed-sha>>
+            echo CYPRESS_baseUrl: $CYPRESS_baseUrl
       - run:
           name: pre-check for params
           command: |
-            TEST_URL=<< pipeline.parameters.test-url >>
-            if [  "x" == "x${TEST_URL}"  ] ;  then
-              echo "No parameters -skipping build ..."
-              exit -1
+            if [  "x" == "x${CYPRESS_baseUrl}"  ] ;  then
+              circleci step halt # does nothing
+              circleci-agent step halt # does nothing
+              echo "   No parameters -skipping build ..."
+              exit 0
             fi
+
       - checkout
-      - run:
-          name: Use parameters
-          command: |
-            echo parameters:
-            echo test-url: << pipeline.parameters.test-url >>
-            echo deployed-sha: <<pipeline.parameters.deployed-sha>>
-      - run:
-          name: build env and parameter diagnosis
-          command: |
-            env | grep CIRCLE | sort
-
-            CYPRESS_baseUrl=<< pipeline.parameters.test-url >>
-            EXPECTED_GIT_SHA=<< pipeline.parameters.deployed-sha >>
-
       - run:
           name: check matching of versions
           command: |
             cd smoketest
 
-            export CYPRESS_baseUrl=<< pipeline.parameters.test-url >>
-            export EXPECTED_GIT_SHA=<< pipeline.parameters.deployed-sha >>
-
-            echo export CYPRESS_baseUrl=$CYPRESS_baseUrl
+            echo export  CYPRESS_baseUrl=$CYPRESS_baseUrl
             echo
             echo _DEBUG:  circle.ci -
-            echo _DEBUG:    CIRCLE_SHA1=$CIRCLE_SHA1
+            echo        CIRCLE_SHA1=$CIRCLE_SHA1
             echo _DEBUG:
             echo _DEBUG:  expecting
             echo export EXPECTED_GIT_SHA=$EXPECTED_GIT_SHA
             echo export GIT_SHA1=${EXPECTED_GIT_SHA:-$CIRCLE_SHA1}
             echo _DEBUG:
             echo _DEBUG:  running
-            echo _DEBUG:     check-deployed-version/check-deployed-version
+            echo      check-deployed-version/check-deployed-version
 
             export GIT_SHA1=${EXPECTED_GIT_SHA:-$CIRCLE_SHA1}
-
             check-deployed-version/check-deployed-version || CHECK_VERSION=$?
 
-            echo _DEBUG: check - result: $CHECK_VERSION
+            echo _  Result:  $CHECK_VERSION
 
             if [  "x-$CHECK_VERSION" == "x-255"  ] ;  then
               echo "Version does not match with $EXPECTED_GIT_SHA"
@@ -102,14 +145,13 @@ jobs:
       - restore_cache:
           keys:
             - cache-smoketest-no-root-cypress-y4-{{ arch }}-{{ checksum "smoketest/yarn.lock" }}
+
       - run:
-          name: smoketest - yarn install
+          name: smoketest - yarn install cypress
           command: |
             cd smoketest
-            yarn install --immutable --check-cache
-            yarn cypress cache path
+            yarn install --immutable
             yarn cypress install
-            yarn cypress verify
       - save_cache:
           key: cache-smoketest-no-root-cypress-y4-{{ arch }}-{{ checksum "smoketest/yarn.lock" }}
           paths:
@@ -118,19 +160,16 @@ jobs:
       - run:
           name: run cypress
           command: |
-            export CYPRESS_baseUrl=<< pipeline.parameters.test-url >>
-            export EXPECTED_GIT_SHA=<< pipeline.parameters.deployed-sha >>
-            export CYPRESS_branch=${CIRCLE_BRANCH}
-
             cd smoketest
             mkdir -p cypress/results
-            yarn dlx cypress info
 
-            echo _DEBUG:  running CYPRESS_branch=${CIRCLE_BRANCH} npm run cy run -- --record
-            # CYPRESS_branch=${CIRCLE_BRANCH} npm run cy run -- --record --key $CYPRESS_API_KEY --reporter junit --reporter-options mochaFile=cypress/results/test-results.xml,toConsole=true
-            # CYPRESS_branch=${CIRCLE_BRANCH} npm run cy run -- --reporter junit --reporter-options mochaFile=cypress/results/test-results.xml,toConsole=true
-            # without reporting to cypress.io
+            echo _DEBUG:  running without reporting to cypress.io:
+            echo   CYPRESS_branch=${CIRCLE_BRANCH} npm run cy run -- --record --key $CYPRESS_API_KEY --reporter junit --reporter-options mochaFile=cypress/results/test-results.xml,toConsole=true
+            echo   CYPRESS_branch=${CIRCLE_BRANCH} npm run cy run -- --reporter junit --reporter-options mochaFile=cypress/results/test-results.xml,toConsole=true
+            echo ...without reporting to cypress.io:
+
             CYPRESS_branch=${CIRCLE_BRANCH} npm run cy run -- --reporter junit --reporter-options mochaFile=cypress/results/test-results.xml,toConsole=true
+
       - store_test_results:
           path: smoketest/cypress/results
       - store_artifacts:
